In [1]:
import random
import numpy as np
from numpy import linalg as la

# 6.1 The Einsum Function

## 1: Trace

In [2]:
A = np.random.rand(5,5)

In [3]:
pred = np.einsum("ii", A)

In [4]:
actual = np.trace(A)

In [5]:
la.norm(actual - pred)

0.0

## 2: Matrix Multiplication

In [6]:
b = np.random.rand(5)

In [7]:
pred = np.einsum("ij,j", A, b)

In [8]:
actual = np.matmul(A, b)

In [9]:
la.norm(actual - pred)

0.0

## 3: Vector Outer Product

In [10]:
a = np.random.rand(5,)
b = np.random.rand(5,)

In [11]:
pred = np.einsum("i,j->ij", a, b)

In [12]:
actual = np.outer(a, b)

In [13]:
la.norm(actual - pred)

0.0

In [14]:
Z1 = [[0.14, 0.07, 0.01], [0.03, 0.11, 0.03], [0.03, 0.11, 0.03], [0.03, 0.04, 0.12]]
Z2 = [[0.01, 0.01, 0.01], [0.01, 0.01, 0.01], [0.01, 0.01, 0.01], [0.04, 0.04, 0.08]]

In [15]:
XY = np.add(Z1, Z2)

In [16]:
XY

array([[0.15, 0.08, 0.02],
       [0.04, 0.12, 0.04],
       [0.04, 0.12, 0.04],
       [0.07, 0.08, 0.2 ]])

In [35]:
first = np.sum(Z1, axis = 1).reshape((-1, 1))
second = np.sum(Z2, axis = 1).reshape((-1, 1))

XZ = np.concatenate((first, second), axis = 1)
XZ

array([[0.22, 0.03],
       [0.17, 0.03],
       [0.17, 0.03],
       [0.19, 0.16]])

In [34]:
first = np.sum(Z1, axis = 0)
second = np.sum(Z2, axis = 0)

YZ = np.stack((second, first))
YZ

array([[0.07, 0.07, 0.11],
       [0.23, 0.33, 0.19]])

In [36]:
PX = np.sum(XZ, axis = 1)
PX

array([0.25, 0.2 , 0.2 , 0.35])

In [41]:
PY = np.sum(YZ, axis = 0)
PY

array([0.3, 0.4, 0.3])

In [40]:
PZ = np.sum(YZ, axis = 1)
PZ

array([0.25, 0.75])

In [42]:
xVal = [-4, 2, 4, 8]
yVal = [0, 3, 6]

In [43]:
XY

array([[0.15, 0.08, 0.02],
       [0.04, 0.12, 0.04],
       [0.04, 0.12, 0.04],
       [0.07, 0.08, 0.2 ]])

In [47]:
sum = 0
for i in np.arange(4):
    for j in np.arange(3):
        sum += xVal[i]*yVal[j]*XY[i][j]
        
sum

13.680000000000001

In [48]:
sum = 0
for i in np.arange(4):
    for j in np.arange(2):
        sum += xVal[i]*yVal[j]*XZ[i][j]
        
sum

4.02

In [49]:
sum = 0
for i in np.arange(2):
    for j in np.arange(3):
        sum += xVal[i]*yVal[j]*YZ[i][j]
        
sum

0.7799999999999996

In [50]:
Z1

[[0.14, 0.07, 0.01],
 [0.03, 0.11, 0.03],
 [0.03, 0.11, 0.03],
 [0.03, 0.04, 0.12]]

In [51]:
Z2

[[0.01, 0.01, 0.01],
 [0.01, 0.01, 0.01],
 [0.01, 0.01, 0.01],
 [0.04, 0.04, 0.08]]

In [56]:
jj = [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
kk = [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]
ll = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
outcomes = []

for l in ll:
    for k in kk:
        for j in jj:
            if l == 1:
                prob = Z1[j-1][k-1]
                outcomes.append(prob)
            if l == 2:
                prob = Z2[j-1][k-1]
                outcomes.append(prob)
len(outcomes)

13824

In [ ]:
F0 = 0
FV = [F0]
for i in np.range(1, 24):
    FV[i] = FV[i-1] + 

In [57]:
a = [1, 2, 3, 4]
np.pad(a, (5, 6), )

array([0, 0, 0, 0, 0, 1, 2, 3, 4, 0, 0, 0, 0, 0, 0])